prompt_technique_name: "critique_n_refine"
unique_model_id: QwQ-32B-Preview
mutate_refine_iterations: 5 # 5
mutation_rounds: 5 # 5
refine_instruction: true
refine_task_eg_iterations: 5 # 5
style_variation: 5 # 5
questions_batch_size: 1
min_correct_count: 20 # 4
max_eval_batches: 30 # 6
top_n: 1
#task_description: "You are a mathematics expert specializing in integer solution math problems. You will be given an mathematics problem that has an integer solution which you need to solve."

#task_description: "You are a once-in a generation coding and mathematics genius. You will be given an integer-solution mathematics problem which you need to solve through any combination of mathematical reasoning and Python code."
#base_instruction: "Solve this mathematical problem by any combination of mathematical reasoning and Python code"
#answer_format: "If you arrive at your integer solution by mathematical reasoning, wrap it in \\boxed{} notation. If you arrive at the solution by Python code, print the final numerical answer at the end of the code block."

task_description: "You are a mathematics expert. You will be given an integer-solution mathematics problem which you need to solve"
base_instruction: "Solve this mathematical problem."
answer_format: "Wrap your final solution in \\boxed{} notation."


seen_set_size: 30
few_shot_count: 0
num_train_examples: 30
generate_reasoning: false
generate_expert_identity: false
generate_intent_keywords: false
