prompt_technique_name: "critique_n_refine"
unique_model_id: QwQ-32B-Preview
mutate_refine_iterations: 7 # 5
mutation_rounds: 7 # 5
refine_instruction: true
refine_task_eg_iterations: 7 # 5
style_variation: 5 # 5
questions_batch_size: 1
min_correct_count: 7 # 4
max_eval_batches: 10 # 6
top_n: 2
#task_description: "You are a mathematics expert specializing in integer solution math problems. You will be given an mathematics problem that has an integer solution which you need to solve."
task_description: "Solve the given integer-solution math problem."
base_instruction: "Let's solve this step by step. Show your reasoning clearly and arrive at a integer numerical answer."
answer_format: "After your solution, wrap only your final numerical answer in \\boxed{} notation."
seen_set_size: 30
few_shot_count: 0
num_train_examples: 30
generate_reasoning: false
generate_expert_identity: true
generate_intent_keywords: true
